// mobile-tauri-svelte/src/screens/kitchen/MealPlanTab.svelte
<script module lang="ts">
  let weekOffset = $state(0);
</script>

<script lang="ts">
  import Card from '../../components/Card.svelte';
  import Icon from '../../components/Icon.svelte';
  import NavRow from '../../components/NavRow.svelte';
  import { Api } from '../../lib/api.svelte';
  import type { MealPlanEntry } from '../../lib/models';
  import { router } from '../../lib/router.svelte';
  import { setStash } from '../../lib/stash';
  import { showError } from '../../lib/toast.svelte';
  import {
    addDays,
    dateStr,
    dayHeader,
    mealOrder,
    mealTypeEmoji,
    mealTypeLabels,
    mondayOf,
    shortDate,
    todayStr,
  } from '../../lib/util';

  let meals = $state.raw<MealPlanEntry[]>([]);

  const monday = $derived(addDays(mondayOf(new Date()), 7 * weekOffset));
  const sunday = $derived(addDays(monday, 6));

  async function load(offset: number) {
    const from = addDays(mondayOf(new Date()), 7 * offset);
    const to = addDays(from, 6);
    meals = (await Api.get('/api/mealplan', {
      from: dateStr(from),
      to: dateStr(to),
    })) as MealPlanEntry[];
  }

  $effect(() => {
    load(weekOffset).catch(showError);
  });

  async function remove(m: MealPlanEntry) {
    try {
      await Api.del(`/api/mealplan/${m.id}`);
      await load(weekOffset);
    } catch (e) {
      showError(e);
    }
  }
</script>

<NavRow
  label={`${shortDate(monday)} – ${shortDate(sunday)}`}
  onprev={() => (weekOffset -= 1)}
  onnext={() => (weekOffset += 1)}
/>
<div class="screen-body">
  {#each Array.from({ length: 7 }, (_, i) => addDays(monday, i)) as day (dateStr(day))}
    {@const ds = dateStr(day)}
    {@const dayMeals = meals
      .filter((m) => m.date === ds)
      .sort((a, b) => mealOrder(a.mealType) - mealOrder(b.mealType))}
    <Card highlight={ds === todayStr()}>
      <div class="day-header">
        <span class="day-title">{dayHeader(day)}</span>
        <button
          class="icon-btn"
          aria-label="Dodaj posiłek"
          onclick={() => {
            setStash(undefined);
            router.push('meal-edit', { date: ds });
          }}
        >
          <Icon name="add-circle" />
        </button>
      </div>
      {#each dayMeals as m (m.id)}
        <button
          class="meal-row"
          onclick={() => {
            setStash(m);
            router.push('meal-edit', { date: ds });
          }}
        >
          <span class="meal-emoji">{mealTypeEmoji[m.mealType] ?? '🍽️'}</span>
          <span class="meal-main">
            <span>{m.recipeTitle ?? m.note}</span>
            <span class="row-sub">{mealTypeLabels[m.mealType] ?? m.mealType}</span>
          </span>
          <span
            class="del"
            role="button"
            tabindex="0"
            aria-label="Usuń"
            onclick={(e) => {
              e.stopPropagation();
              remove(m);
            }}
            onkeydown={(e) => {
              if (e.key === 'Enter') {
                e.stopPropagation();
                remove(m);
              }
            }}
          >
            <Icon name="trash" size={19} color="var(--muted)" />
          </span>
        </button>
      {/each}
    </Card>
  {/each}
</div>

<style>
  .day-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
  }

  .day-title {
    font-weight: 800;
  }

  .meal-row {
    display: flex;
    align-items: center;
    padding: 6px 0;
    width: 100%;
    text-align: left;
  }

  .meal-emoji {
    font-size: 20px;
    margin-right: 10px;
  }

  .meal-main {
    flex: 1;
    min-width: 0;
    display: flex;
    flex-direction: column;
  }

  .del {
    display: inline-flex;
    padding: 4px;
  }
</style>

// mobile/components/kitchen/MealPlanTab.tsx
import { Ionicons } from '@expo/vector-icons';
import { router, useFocusEffect } from 'expo-router';
import React, { useCallback, useState } from 'react';
import { RefreshControl, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';

import { Api } from '../../lib/api';
import type { MealPlanEntry } from '../../lib/models';
import { setStash } from '../../lib/stash';
import { colors } from '../../lib/theme';
import {
  addDays,
  dateStr,
  dayHeader,
  mealOrder,
  mealTypeEmoji,
  mealTypeLabels,
  mondayOf,
  shortDate,
  todayStr,
} from '../../lib/util';
import { Card, HeaderIcon, NavRow, showError } from '../ui';

export default function MealPlanTab() {
  const [weekOffset, setWeekOffset] = useState(0);
  const [meals, setMeals] = useState<MealPlanEntry[]>([]);
  const [refreshing, setRefreshing] = useState(false);

  const monday = addDays(mondayOf(new Date()), 7 * weekOffset);
  const sunday = addDays(monday, 6);

  const load = useCallback(async () => {
    const from = addDays(mondayOf(new Date()), 7 * weekOffset);
    const to = addDays(from, 6);
    const res = (await Api.get('/api/mealplan', {
      from: dateStr(from),
      to: dateStr(to),
    })) as MealPlanEntry[];
    setMeals(res);
  }, [weekOffset]);

  useFocusEffect(
    useCallback(() => {
      load().catch(showError);
    }, [load]),
  );

  const onRefresh = useCallback(async () => {
    setRefreshing(true);
    try {
      await load();
    } catch (e) {
      showError(e);
    } finally {
      setRefreshing(false);
    }
  }, [load]);

  const remove = async (m: MealPlanEntry) => {
    try {
      await Api.del(`/api/mealplan/${m.id}`);
      await load();
    } catch (e) {
      showError(e);
    }
  };

  return (
    <View style={{ flex: 1 }}>
      <NavRow
        label={`${shortDate(monday)} – ${shortDate(sunday)}`}
        onPrev={() => setWeekOffset(weekOffset - 1)}
        onNext={() => setWeekOffset(weekOffset + 1)}
      />
      <ScrollView
        contentContainerStyle={{ paddingHorizontal: 16, paddingBottom: 24 }}
        refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} />}
      >
        {Array.from({ length: 7 }, (_, i) => {
          const day = addDays(monday, i);
          const ds = dateStr(day);
          const isToday = ds === todayStr();
          const dayMeals = meals
            .filter((m) => m.date === ds)
            .sort((a, b) => mealOrder(a.mealType) - mealOrder(b.mealType));
          return (
            <Card key={ds} style={isToday ? { backgroundColor: colors.primaryContainer } : undefined}>
              <View style={styles.dayHeader}>
                <Text style={styles.dayTitle}>{dayHeader(day)}</Text>
                <HeaderIcon
                  name="add-circle-outline"
                  onPress={() => {
                    setStash(undefined);
                    router.push({ pathname: '/meal-edit', params: { date: ds } });
                  }}
                />
              </View>
              {dayMeals.map((m) => (
                <TouchableOpacity
                  key={m.id}
                  style={styles.mealRow}
                  onPress={() => {
                    setStash(m);
                    router.push({ pathname: '/meal-edit', params: { date: ds } });
                  }}
                >
                  <Text style={{ fontSize: 20, marginRight: 10 }}>
                    {mealTypeEmoji[m.mealType] ?? '🍽️'}
                  </Text>
                  <View style={{ flex: 1 }}>
                    <Text style={{ color: colors.text }}>{m.recipeTitle ?? m.note}</Text>
                    <Text style={{ color: colors.muted, fontSize: 12 }}>
                      {mealTypeLabels[m.mealType] ?? m.mealType}
                    </Text>
                  </View>
                  <TouchableOpacity onPress={() => remove(m)} hitSlop={8}>
                    <Ionicons name="trash-outline" size={19} color={colors.muted} />
                  </TouchableOpacity>
                </TouchableOpacity>
              ))}
            </Card>
          );
        })}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  dayHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  dayTitle: { fontWeight: '800', color: colors.text },
  mealRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 6 },
});
